# Generated by Django 2.1.2 on 2018-10-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_animal_feeders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='amount',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='animal',
            name='x',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
