# Generated by Django 2.1.2 on 2018-10-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_animal_feeders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='a_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
