# Generated by Django 2.1.2 on 2018-10-18 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_animal_feeders', '0002_auto_20181018_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='owner',
        ),
    ]
