# Generated by Django 2.1.2 on 2018-10-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_animal_feeders', '0004_auto_20181011_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='x',
        ),
        migrations.AddField(
            model_name='animal',
            name='breakfast',
            field=models.TimeField(default='%H:%M'),
        ),
        migrations.AddField(
            model_name='animal',
            name='dinner',
            field=models.TimeField(default='%H:%M'),
        ),
        migrations.AddField(
            model_name='animal',
            name='lunch',
            field=models.TimeField(default='%H:%M'),
        ),
    ]
