# Generated by Django 2.1.2 on 2018-10-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_animal_feeders', '0006_auto_20181011_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='animal',
            name='dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='animal',
            name='lunch',
            field=models.BooleanField(default=False),
        ),
    ]
